### ISSUE TITLE
cardList

### ISSUE THREAD

**Issue by gabean13** [Capstone-4Potato/backend-server#2]
## Description
main 화면의 음절, 단어, 문장들의 세부 카테고리에 맞게 학습카드 리스트 제공해준다.

## Todo
- [x] 카드테이블의 pronunciation을 초성 중성 종성으로 뽑아내기(ETC 참고)
- [x] 카테고리에 따른 학습카드 리스트
- [x] 북마크 기능 
- [x] 취약음 갱신에 따른 취약음 카드 리스트 갱신 (취약음 테스트 완성 시 진행)

#### 카드테이블의 pronunciation을 초성 중성 종성으로 뽑아내기
ex ) 꽃다발 [ 꼳따발 ]=> ㄲ ㅗ ㄷ ㄸ ㅏ ㅂ ㅏ ㄹ
각 음소와 phonemes 테이블의 음소가 일치하도록 아이디 저장
- 추후 취약음 유무와 학습카드 추천에 사용

#### 관련 화면
![image](https://github.com/Capstone-4Potato/backend-server/assets/108220648/b8f6f4eb-d993-43ca-a91c-6acd6137253f)

![image](https://github.com/Capstone-4Potato/backend-server/assets/108220648/fb39550a-4327-401c-8723-52cc262c3fb8)
