### ISSUE TITLE
custom_card

### ISSUE THREAD

**Issue by gabean13** [Capstone-4Potato/backend-server#22]
## Description
사용자가 직접 원하는 문장을 입력하면 해당 커스텀 카드를 생성하고, 생성 한 문장을 삭제를 하고 싶으면 삭제한다.
** 문장 생성 **
문장 입력 시 해당 카드의 올바른 문장 발음을 인공지능 서버로부터 받아온 뒤 데이터베이스 custom_card에 저장한다.
사용자는 최대 10개의 문장을 생성할 수 있다.

** 문장 삭제 **
사용자가 본인이 생성한 문장을 삭제 요청을 하면 데이터베이스에서 삭제한다.

** 문장 클릭 **
학습을 위해 사용자가 커스텀문장을 클릭 시 학습 카드를 제공한다.

## Todo
- [x] 사용자가 문장 입력 시 학습 문장 카드 생성 API 만들기
- [x] 인공지능 서버에서 올바른 문장 발음 받아오기
- [x] 문장 삭제요청 시 데이터베이스에서 문장 삭제하기
- [x] 사용자가 커스텀 문장 학습를 원할 때 API 만들기
