### ISSUE TITLE
weakSound

### ISSUE THREAD

**Issue by yoownny** [Capstone-4Potato/backend-server#28]
## Description
취약음 테스트 후 사용자에게 취약음 제공한다.
사용자는 자신의 취약음을 추가, 삭제할 수 있고 재시도할 수 있다.

## Todo
- [x] 프론트와 취약음 테스트 연결
- [x] 인공지능과 취약음 테스트 연결
- [x] 사용자 취약음 제공
- [x] 취약음 삭제 기능 제공
