### ISSUE TITLE
signIn

### ISSUE THREAD

**Issue by yoownny** [Capstone-4Potato/backend-server#3]
## Description
닉네임, 성별, 나이, 이메일을 받아서 회원가입을 완료한다.
회원을 탈퇴할 경우 닉네임을 따라치고 맞으면 탈퇴한다.

## Todo
- [x] user table 생성하기
- [x] 회원 정보(이름, 나이, 성별, 이메일) 받아오기
- [x] 회원 정보(이름, 나이, 성별) 수정하기
- [x] 회원 정보 삭제하기

## ETC
한 이메일로는 1번만 가입이 가능
