### ISSUE TITLE
weakSoundTest

### ISSUE THREAD

**Issue by yoownny** [Capstone-4Potato/backend-server#5]
## Description
30단어로 취약음 테스트를 진행해서 
사용자가 발음하지 못하는 음소를 5개를 뽑아서
사용자 취약음 테이블에 저장한다.

## Todo
- [X]  인공지능으로 사용자 음성과 카드 텍스트 보내기
- [X]  인공지능으로부터 틀린 음소 받기
- [x]  프론트로부터 사용자 음성 받기
- [x]  인공지능으로부터 받은 응답의 음소를 음소id로 변환하기
- [x]  map으로 저장하기
- [x]   프론트로부터 취약음 테스트 종료 신호 받기
- [x]  많이 틀린 취약음소 5개 선택하기
- [x]  사용자 취약음 테이블에 연결하기

## ETC
음성은 wav 파일 형식으로 전송한다.
인공지능과는 json 파일 형식으로 소통한다.
