### ISSUE TITLE
Feat : SaveVoiceInServer

### ISSUE THREAD

**Issue by gabean13** [Capstone-4Potato/backend-server#68]
## Description
동일한 음성을 계속 생성하여 TTS API를 소모하는 문제를 해결하기 위해 
데이터베이스에 있는 카드들은 음성을 서버에 저장하고 보내주는 걸로 로직 변경

## Todo
- [x] 음성이 서버에 저장되어 있는지 확인
- [x] 서버에 저장되어 있지 않으면 api호출하여 음성 6개 저장
- [x] 저장된 음성을 보내주는 걸로 로직 변경
- [x] 데이터베이스에 카드가 추가되면 자동으로 서버에서 음성 저장
- [ ] 테스트 코드 작성
