### ISSUE TITLE
Refactor : code 정리 & Swagger 추가

### ISSUE THREAD

**Issue by yoownny** [Capstone-4Potato/backend-server#69]
## Description
code를 가독성 높게 정리를 하고, Swagger 코드를 추가하여 자동 api 명세서 작성을 하려고 한다.

## Todo
- [x] LearningInfo code 구조 정리
- [x] Profile code 구조 정리
- [x] Swagger 코드 추가
- [x] log 정리
