### ISSUE TITLE
cardInfo

### ISSUE THREAD

**Issue by gabean13** [Capstone-4Potato/backend-server#7]
## Description
사용자가 원하는 Card를 누르면 그 Card에 필요한 정보(카드 고유 Id, 카드 text, 발음 text)와 한국어 발음 음성을 제공한다.
한국어 발음 음성은 사용자 연령대와 성별에 따라 제공하고 이 음성은 인공지능 서버에서 생성(TTS)하여 프론트로 전달한다.

## Todo
- [x] 카드 정보 요청 API  (프론트 <-> 백엔드) 
- [x] 음성 생성 요청 API (백엔드 <->인공지능 서버 )
- [x] 카드 정보 제공
- [x] 카드 음성 제공

## ETC
해당 화면
![image](https://github.com/Capstone-4Potato/backend-server/assets/108220648/0f40254a-cbc3-4ef5-8862-9820c9c1032a)
