### ISSUE TITLE
Feat : log

### ISSUE THREAD

**Issue by yoownny** [Capstone-4Potato/backend-server#77]
## Description
Log4j2를 이용하여 데이터베이스에 log를 기록하려 합니다.

## Todo
- [x] Log4j2 추가
- [x] 코드에 log entity 작성
- [x] 데이터베이스와 코드 연결
- [x] exception_info 데이터베이스에 작성

- [x] log 저장 규칙 세워서 저장
- [ ] Error의 경우 이메일/카톡 알림 기능 추가
