### ISSUE TITLE
User 테이블 수정

### ISSUE THREAD

**Issue by yoownny** [Capstone-4Potato/backend-server#80]
## Todo
- [x] User 테이블에 사용자 레벨, 경험치 추가
- [x] Home 정보 조회 API -> Swagger 작성
- [x] 사용자 레벨 조회 API 생성
- [x] 경험치 업데이트 API 생성

**Comment by yoownny** [comment]
[Feat} : UserLevel, UserAttendance, Level 테이블 생성 완료 (#80)
